# Generated by Django 4.1.5 on 2023-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
